// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/juglar.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JuglarService_HealthCheck_FullMethodName      = "/juglar.JuglarService/HealthCheck"
	JuglarService_ObtenerHistorial_FullMethodName = "/juglar.JuglarService/ObtenerHistorial"
	JuglarService_EnviarMensaje_FullMethodName    = "/juglar.JuglarService/EnviarMensaje"
)

// JuglarServiceClient is the client API for JuglarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JuglarServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ObtenerHistorial(ctx context.Context, in *HistorialRequest, opts ...grpc.CallOption) (*HistorialResponse, error)
	EnviarMensaje(ctx context.Context, in *MensajeRequest, opts ...grpc.CallOption) (*MensajeResponse, error)
}

type juglarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJuglarServiceClient(cc grpc.ClientConnInterface) JuglarServiceClient {
	return &juglarServiceClient{cc}
}

func (c *juglarServiceClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, JuglarService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *juglarServiceClient) ObtenerHistorial(ctx context.Context, in *HistorialRequest, opts ...grpc.CallOption) (*HistorialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistorialResponse)
	err := c.cc.Invoke(ctx, JuglarService_ObtenerHistorial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *juglarServiceClient) EnviarMensaje(ctx context.Context, in *MensajeRequest, opts ...grpc.CallOption) (*MensajeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MensajeResponse)
	err := c.cc.Invoke(ctx, JuglarService_EnviarMensaje_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JuglarServiceServer is the server API for JuglarService service.
// All implementations must embed UnimplementedJuglarServiceServer
// for forward compatibility.
type JuglarServiceServer interface {
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	ObtenerHistorial(context.Context, *HistorialRequest) (*HistorialResponse, error)
	EnviarMensaje(context.Context, *MensajeRequest) (*MensajeResponse, error)
	mustEmbedUnimplementedJuglarServiceServer()
}

// UnimplementedJuglarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJuglarServiceServer struct{}

func (UnimplementedJuglarServiceServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedJuglarServiceServer) ObtenerHistorial(context.Context, *HistorialRequest) (*HistorialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerHistorial not implemented")
}
func (UnimplementedJuglarServiceServer) EnviarMensaje(context.Context, *MensajeRequest) (*MensajeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnviarMensaje not implemented")
}
func (UnimplementedJuglarServiceServer) mustEmbedUnimplementedJuglarServiceServer() {}
func (UnimplementedJuglarServiceServer) testEmbeddedByValue()                       {}

// UnsafeJuglarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JuglarServiceServer will
// result in compilation errors.
type UnsafeJuglarServiceServer interface {
	mustEmbedUnimplementedJuglarServiceServer()
}

func RegisterJuglarServiceServer(s grpc.ServiceRegistrar, srv JuglarServiceServer) {
	// If the following call panics, it indicates UnimplementedJuglarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JuglarService_ServiceDesc, srv)
}

func _JuglarService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JuglarServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JuglarService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JuglarServiceServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JuglarService_ObtenerHistorial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistorialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JuglarServiceServer).ObtenerHistorial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JuglarService_ObtenerHistorial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JuglarServiceServer).ObtenerHistorial(ctx, req.(*HistorialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JuglarService_EnviarMensaje_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MensajeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JuglarServiceServer).EnviarMensaje(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JuglarService_EnviarMensaje_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JuglarServiceServer).EnviarMensaje(ctx, req.(*MensajeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JuglarService_ServiceDesc is the grpc.ServiceDesc for JuglarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JuglarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "juglar.JuglarService",
	HandlerType: (*JuglarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _JuglarService_HealthCheck_Handler,
		},
		{
			MethodName: "ObtenerHistorial",
			Handler:    _JuglarService_ObtenerHistorial_Handler,
		},
		{
			MethodName: "EnviarMensaje",
			Handler:    _JuglarService_EnviarMensaje_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/juglar.proto",
}
