// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/juglar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_juglar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Uptime        string                 `protobuf:"bytes,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_juglar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *HealthResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type HistorialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistorialRequest) Reset() {
	*x = HistorialRequest{}
	mi := &file_proto_juglar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistorialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorialRequest) ProtoMessage() {}

func (x *HistorialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorialRequest.ProtoReflect.Descriptor instead.
func (*HistorialRequest) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{2}
}

type MensajeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remitente     string                 `protobuf:"bytes,1,opt,name=remitente,proto3" json:"remitente,omitempty"`
	Contenido     string                 `protobuf:"bytes,2,opt,name=contenido,proto3" json:"contenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensajeRequest) Reset() {
	*x = MensajeRequest{}
	mi := &file_proto_juglar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensajeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeRequest) ProtoMessage() {}

func (x *MensajeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeRequest.ProtoReflect.Descriptor instead.
func (*MensajeRequest) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{3}
}

func (x *MensajeRequest) GetRemitente() string {
	if x != nil {
		return x.Remitente
	}
	return ""
}

func (x *MensajeRequest) GetContenido() string {
	if x != nil {
		return x.Contenido
	}
	return ""
}

type MensajeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensajeResponse) Reset() {
	*x = MensajeResponse{}
	mi := &file_proto_juglar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensajeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeResponse) ProtoMessage() {}

func (x *MensajeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeResponse.ProtoReflect.Descriptor instead.
func (*MensajeResponse) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{4}
}

func (x *MensajeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MensajeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remitente     string                 `protobuf:"bytes,1,opt,name=remitente,proto3" json:"remitente,omitempty"`
	Contenido     string                 `protobuf:"bytes,2,opt,name=contenido,proto3" json:"contenido,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MensajeItem) Reset() {
	*x = MensajeItem{}
	mi := &file_proto_juglar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MensajeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensajeItem) ProtoMessage() {}

func (x *MensajeItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensajeItem.ProtoReflect.Descriptor instead.
func (*MensajeItem) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{5}
}

func (x *MensajeItem) GetRemitente() string {
	if x != nil {
		return x.Remitente
	}
	return ""
}

func (x *MensajeItem) GetContenido() string {
	if x != nil {
		return x.Contenido
	}
	return ""
}

func (x *MensajeItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type HistorialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensajes      []*MensajeItem         `protobuf:"bytes,1,rep,name=mensajes,proto3" json:"mensajes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistorialResponse) Reset() {
	*x = HistorialResponse{}
	mi := &file_proto_juglar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistorialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorialResponse) ProtoMessage() {}

func (x *HistorialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_juglar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorialResponse.ProtoReflect.Descriptor instead.
func (*HistorialResponse) Descriptor() ([]byte, []int) {
	return file_proto_juglar_proto_rawDescGZIP(), []int{6}
}

func (x *HistorialResponse) GetMensajes() []*MensajeItem {
	if x != nil {
		return x.Mensajes
	}
	return nil
}

var File_proto_juglar_proto protoreflect.FileDescriptor

const file_proto_juglar_proto_rawDesc = "" +
	"\n" +
	"\x12proto/juglar.proto\x12\x06juglar\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\tR\x06uptime\"\x12\n" +
	"\x10HistorialRequest\"L\n" +
	"\x0eMensajeRequest\x12\x1c\n" +
	"\tremitente\x18\x01 \x01(\tR\tremitente\x12\x1c\n" +
	"\tcontenido\x18\x02 \x01(\tR\tcontenido\")\n" +
	"\x0fMensajeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"g\n" +
	"\vMensajeItem\x12\x1c\n" +
	"\tremitente\x18\x01 \x01(\tR\tremitente\x12\x1c\n" +
	"\tcontenido\x18\x02 \x01(\tR\tcontenido\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"D\n" +
	"\x11HistorialResponse\x12/\n" +
	"\bmensajes\x18\x01 \x03(\v2\x13.juglar.MensajeItemR\bmensajes2\xd8\x01\n" +
	"\rJuglarService\x12<\n" +
	"\vHealthCheck\x12\x15.juglar.HealthRequest\x1a\x16.juglar.HealthResponse\x12G\n" +
	"\x10ObtenerHistorial\x12\x18.juglar.HistorialRequest\x1a\x19.juglar.HistorialResponse\x12@\n" +
	"\rEnviarMensaje\x12\x16.juglar.MensajeRequest\x1a\x17.juglar.MensajeResponseB_\n" +
	"\n" +
	"com.juglarB\vJuglarProtoP\x01Z\fjuglar/proto\xa2\x02\x03JXX\xaa\x02\x06Juglar\xca\x02\x06Juglar\xe2\x02\x12Juglar\\GPBMetadata\xea\x02\x06Juglarb\x06proto3"

var (
	file_proto_juglar_proto_rawDescOnce sync.Once
	file_proto_juglar_proto_rawDescData []byte
)

func file_proto_juglar_proto_rawDescGZIP() []byte {
	file_proto_juglar_proto_rawDescOnce.Do(func() {
		file_proto_juglar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_juglar_proto_rawDesc), len(file_proto_juglar_proto_rawDesc)))
	})
	return file_proto_juglar_proto_rawDescData
}

var file_proto_juglar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_juglar_proto_goTypes = []any{
	(*HealthRequest)(nil),     // 0: juglar.HealthRequest
	(*HealthResponse)(nil),    // 1: juglar.HealthResponse
	(*HistorialRequest)(nil),  // 2: juglar.HistorialRequest
	(*MensajeRequest)(nil),    // 3: juglar.MensajeRequest
	(*MensajeResponse)(nil),   // 4: juglar.MensajeResponse
	(*MensajeItem)(nil),       // 5: juglar.MensajeItem
	(*HistorialResponse)(nil), // 6: juglar.HistorialResponse
}
var file_proto_juglar_proto_depIdxs = []int32{
	5, // 0: juglar.HistorialResponse.mensajes:type_name -> juglar.MensajeItem
	0, // 1: juglar.JuglarService.HealthCheck:input_type -> juglar.HealthRequest
	2, // 2: juglar.JuglarService.ObtenerHistorial:input_type -> juglar.HistorialRequest
	3, // 3: juglar.JuglarService.EnviarMensaje:input_type -> juglar.MensajeRequest
	1, // 4: juglar.JuglarService.HealthCheck:output_type -> juglar.HealthResponse
	6, // 5: juglar.JuglarService.ObtenerHistorial:output_type -> juglar.HistorialResponse
	4, // 6: juglar.JuglarService.EnviarMensaje:output_type -> juglar.MensajeResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_juglar_proto_init() }
func file_proto_juglar_proto_init() {
	if File_proto_juglar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_juglar_proto_rawDesc), len(file_proto_juglar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_juglar_proto_goTypes,
		DependencyIndexes: file_proto_juglar_proto_depIdxs,
		MessageInfos:      file_proto_juglar_proto_msgTypes,
	}.Build()
	File_proto_juglar_proto = out.File
	file_proto_juglar_proto_goTypes = nil
	file_proto_juglar_proto_depIdxs = nil
}
